# Generated by Django 5.2.5 on 2025-08-19 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='participant',
            old_name='organization',
            new_name='parish',
        ),
        migrations.AddField(
            model_name='participant',
            name='archdeaconry',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
