# Generated by Django 5.2.5 on 2025-08-19 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_rename_organization_participant_parish_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='role',
            field=models.CharField(blank=True, choices=[('Director', 'Director'), ('DeputyDirector', 'Deputy Director'), ('Chaplain', 'Chaplain'), ('Executive', 'Executive'), ('Leader', 'Leader'), ('Delegate', 'Delegate'), ('Special Guest', 'Special Guest'), ('Vendor', 'Vendor')], max_length=50),
        ),
        migrations.AlterField(
            model_name='participant',
            name='archdeaconry',
            field=models.CharField(blank=True, choices=[('Ago-Iwoye', 'Ago-Iwoye'), ('Ago-South', 'Ago-South'), ('Oru', 'Oru'), ('Awa', 'Awa'), ('Ifelodun', 'Ifelodun'), ('Cathedral', 'Cathedral'), ('Ojowo', 'Ojowo'), ('Oke-Sopin', 'Oke-Sopin'), ('Oke-Agbo', 'Oke-Agbo'), ('Atikori', 'Atikori'), ('Japara', 'Japara')], max_length=100),
        ),
    ]
