# Generated by Django 5.2.5 on 2025-08-19 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0003_participant_role_alter_participant_archdeaconry'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='camp_id',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='participant',
            name='dob',
            field=models.DateField(default='2025-10-10'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='participant',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default='Male', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='participant',
            name='room_no',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
    ]
