# Generated by Django 5.2.5 on 2025-08-19 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0004_participant_camp_id_participant_dob_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
