# Generated by Django 5.2.5 on 2025-08-19 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0005_alter_participant_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='role',
            field=models.CharField(blank=True, choices=[('Director', 'Director'), ('DeputyDirector', 'Deputy Director'), ('Chaplain', 'Chaplain'), ('Special Guest', 'Special Guest'), ('Vendor', 'Vendor'), ('Executive', 'Executive'), ('Leader', 'Leader'), ('Delegate', 'Delegate')], max_length=50),
        ),
    ]
