# Generated by Django 5.2.5 on 2025-08-20 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0006_alter_participant_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='archdeaconry',
            field=models.CharField(choices=[('Ago-Iwoye', 'Ago-Iwoye'), ('Ago-South', 'Ago-South'), ('Oru', 'Oru'), ('Awa', 'Awa'), ('Ifelodun', 'Ifelodun'), ('Cathedral', 'Cathedral'), ('Ojowo', 'Ojowo'), ('Oke-Sopin', 'Oke-Sopin'), ('Oke-Agbo', 'Oke-Agbo'), ('Atikori', 'Atikori'), ('Japara', 'Japara')], max_length=100),
        ),
        migrations.AlterField(
            model_name='participant',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='participant',
            name='parish',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='participant',
            name='phone',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AlterField(
            model_name='participant',
            name='role',
            field=models.CharField(choices=[('Director', 'Director'), ('DeputyDirector', 'Deputy Director'), ('Chaplain', 'Chaplain'), ('Special Guest', 'Special Guest'), ('Vendor', 'Vendor'), ('Delegate', 'Delegate'), ('Leader', 'Leader'), ('Executive', 'Executive')], max_length=50),
        ),
    ]
